import { ModuleType } from "@/@types/appContext";

const prompts = {
    generateModules: (themeStudy: string) => {
        return `Por favor, monte um plano de estudo personalizado para o tema: '${themeStudy}'. Você deve montar módulos para os diferentes temas a serem abordados. Cada módulo deve ser rico em conteúdo, contudo, por enquanto você deve devolver somente o título e uma breve descrição do que será abordado em cada módulo. Por favor devolva o resultado em json. Limite-se a no máximo 6 módulos. Exemplo de resposta: 'planoEstudo: [{title,description},{...},....]'. RESPOSTA:`;
    },
    generateModule: (module: ModuleType) => {
        return `Por favor, monte um plano de estudo personalizado para o tema: ${module.description}. Você deve montar módulos para os diferentes temas a serem abordados. Cada módulo deve ser rico em conteúdo, contendo imagens para ilustrar as informações quando possível, ou quando não for possível, um link para uma imagem. Por favor devolva o resultado em json. Limite-se a no máximo 12 módulos. Exemplo de resposta: 'planoEstudo: [{title,html},{...},....]' RESPOSTA:`;
    }
};

export default prompts;

// [
//     {
//         "title": "Módulo 1: Introdução e Pré-História",
//         "html": "<h2>1. Introdução</h2> <p>Neste módulo, vamos explorar a localização geográfica de Portugal e sua importância histórica, além de traçar uma linha do tempo geral da história portuguesa, desde seus primórdios até os dias atuais.</p> <h3>1.1 Localização Estratégica</h3> <p>Portugal ocupa uma posição estratégica na Península Ibérica, com uma longa costa atlântica. Essa localização privilegiada moldou sua história, cultura e economia ao longo dos séculos, favorecendo a navegação, o comércio e o contato com diferentes povos.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Location_Portugal.svg/1024px-Location_Portugal.svg.png' alt='Mapa de Portugal'> <h3>1.2 Linha do Tempo Geral</h3> <p>Abordaremos os principais períodos da história portuguesa, desde a pré-história até a atualidade, estabelecendo uma base cronológica para os módulos seguintes.</p> <h2>2. Pré-História e Povos Antigos</h2> <p>Neste ponto, investigaremos as primeiras culturas que habitaram o território português, incluindo:</p> <h3>2.1 Paleolítico e Neolítico</h3> <p>Evidências arqueológicas revelam a presença humana em Portugal desde o Paleolítico. Exploraremos os vestígios deixados por esses primeiros habitantes, seus modos de vida e a transição para o Neolítico, com o desenvolvimento da agricultura.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cromeleque_dos_Almendres_%285%29.jpg/800px-Cromeleque_dos_Almendres_%285%29.jpg' alt='Cromeleque dos Almendres'> <h3>2.2 Iberos, Celtas e Outros Povos</h3> <p>Abordaremos a chegada de diferentes povos à Península Ibérica, como os Iberos e os Celtas, que contribuíram para a formação da cultura e da língua portuguesa.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Guerreiro_lusitano_%283%29.jpg/1024px-Guerreiro_lusitano_%283%29.jpg' alt='Guerreiro Lusitano'>"
//     },
//     {
//         "title": "Módulo 2:  Portugal Romano e Visigótico",
//         "html": "<h2>1. Romanização da Lusitânia</h2> <p>Neste módulo, vamos mergulhar na conquista romana da Península Ibérica e o impacto duradouro na cultura, língua e sociedade portuguesa.</p> <h3>1.1 Conquista e Resistência</h3> <p>A conquista romana da Lusitânia, região que corresponde a grande parte do atual Portugal, não foi fácil. Exploraremos as Guerras Lusitanas, com destaque para a figura de Viriato, símbolo da resistência lusitana à dominação romana.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Viriathus.jpg/800px-Viriathus.jpg' alt='Estátua de Viriato'> <h3>1.2 Legado Romano</h3> <p>A presença romana deixou marcas profundas em Portugal, desde a língua latina, base do português, até a infraestrutura, como estradas, pontes e cidades. Abordaremos a vida em Portugal sob o domínio romano, o desenvolvimento urbano e a difusão do cristianismo.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Conimbriga_Ruinas_Romanas_%281%29.jpg/1024px-Conimbriga_Ruinas_Romanas_%281%29.jpg' alt='Ruínas romanas de Conimbriga'> <h2>2. Período Visigótico</h2> <p>Com a queda do Império Romano, a Península Ibérica foi ocupada pelos Visigodos. Exploraremos:</p> <h3>2.1 Ascensão e Queda dos Visigodos</h3> <p>Analisaremos a formação do Reino Visigótico, sua organização social, cultura e as disputas internas que levaram ao seu declínio.</p> <h3>2.2 Influência na Cultura e Religião</h3> <p>Abordaremos a influência dos Visigodos na cultura e religião de Portugal, com destaque para a conversão ao cristianismo e o desenvolvimento da arte visigótica.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Tesouro_de_Guarrazar_1.jpg/1024px-Tesouro_de_Guarrazar_1.jpg' alt='Tesouro de Guarrazar'>"
//     },
//     {
//         "title": "Módulo 3: Ascensão de Portugal e Reconquista",
//         "html": "<h2>1. Dominação Muçulmana e Reconquista Cristã</h2> <p>Este módulo abordará a conquista muçulmana da Península Ibérica no século VIII e o longo processo de Reconquista Cristã, que culminou na formação do Reino de Portugal.</p> <h3>1.1 Chegada dos Mouros</h3> <p>Analisaremos a invasão muçulmana da Península Ibérica, a formação do Al-Andalus e o impacto da cultura islâmica na região, incluindo Portugal.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Mezquita_de_Cordoba_2.jpg/1024px-Mezquita_de_Cordoba_2.jpg' alt='Mesquita de Córdoba'> <h3>1.2 Reinos Cristãos e a Luta pela Reconquista</h3> <p>Exploraremos o surgimento dos reinos cristãos no norte da Península Ibérica, como o Reino Astur-Leonês, e a longa luta pela Reconquista. Abordaremos as principais batalhas, figuras importantes e a expansão gradual do território cristão.</p> <h3>1.3 Surgimento do Condado Portucalense</h3> <p>Analisaremos a formação do Condado Portucalense, um feudo do Reino de Leão, no século XI, e a figura de D. Afonso Henriques, que liderou a luta pela independência de Portugal.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Afonso_Henriques_by_Jose_Vital_Branco_Malhoa.jpg/1024px-Afonso_Henriques_by_Jose_Vital_Branco_Malhoa.jpg' alt='Afonso Henriques'>"
//     },
//     {
//         "title": "Módulo 4:  Formação do Reino e Dinastia de Borgonha",
//         "html": "<h2>1. Independência e Dinastia de Borgonha</h2> <p>Neste módulo, vamos explorar a consolidação do Reino de Portugal, o papel da Dinastia de Borgonha em sua expansão territorial e desenvolvimento cultural.</p> <h3>1.1  Afonso Henriques e o Reconhecimento de Portugal</h3> <p>Abordaremos a figura de D. Afonso Henriques, a Batalha de São Mamede em 1128, que marcou o início da independência portuguesa, e o reconhecimento de Portugal como reino independente pelo Papa em 1179.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Batalha_de_Sao_Mamede_%28Guimaraes%29_-_Portugal.jpg/800px-Batalha_de_Sao_Mamede_%28Guimaraes%29_-_Portugal.jpg' alt='Batalha de São Mamede'> <h3>1.2 Expansão Territorial e Consolidação Interna</h3> <p>Exploraremos a continuação da Reconquista, com a conquista de Lisboa em 1147 e a expansão para o sul, até o Algarve. Abordaremos também a organização administrativa do reino, a formação das cortes e o desenvolvimento da cultura portuguesa.</p> <h3>1.3 Dinastia de Borgonha: Ascensão e Apogeu</h3> <p>Analisaremos a ascensão da Dinastia de Borgonha ao trono português no século XII e seu papel no desenvolvimento cultural e econômico do reino. Abordaremos figuras importantes como D. Dinis, rei poeta que fundou a Universidade de Coimbra.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/D._Dinis_I_%281261-1325%29%2C_rei_de_Portugal_%28Mosteiro_dos_Jerónimos%29.jpg/800px-D._Dinis_I_%281261-1325%29%2C_rei_de_Portugal_%28Mosteiro_dos_Jerónimos%29.jpg' alt='D. Dinis I'>"
//     },
//     {
//         "title": "Módulo 5:  Descobrimentos e Império Português",
//         "html": "<h2>1. Era dos Descobrimentos: Portugal no Palco Mundial</h2> <p>Neste módulo, vamos mergulhar na Era dos Descobrimentos, período crucial na história de Portugal e do mundo, com foco nos avanços tecnológicos, nas grandes viagens marítimas e na formação do Império Português.</p> <h3>1.1  Contexto Histórico e Motivações</h3> <p>Exploraremos o contexto histórico que levou aos Descobrimentos, como a busca por novas rotas comerciais para o Oriente, o espírito da Renascença, os avanços tecnológicos em navegação e a centralização do poder real em Portugal.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Astrolabe_Florence.jpg/800px-Astrolabe_Florence.jpg' alt='Astrolábio'> <h3>1.2 Pioneiros e Primeiras Conquistas</h3> <p>Abordaremos os pioneiros dos Descobrimentos, como o Infante D. Henrique, e as primeiras conquistas portuguesas, como a conquista de Ceuta em 1415 e a exploração da costa africana, com a chegada ao Cabo da Boa Esperança em 1488 por Bartolomeu Dias.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Infante_D._Henrique%2C_o_Navegador.jpg/1024px-Infante_D._Henrique%2C_o_Navegador.jpg' alt='Infante D. Henrique'> <h3>1.3 Caminho Marítimo para a Índia</h3> <p>Analisaremos a épica viagem de Vasco da Gama, que em 1498 chegou à Índia, abrindo uma nova rota comercial para o Oriente e marcando o início da presença portuguesa no Oceano Índico.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Vasco_da_Gama%2C_by_Antonio_Manuel_da_Fonseca.jpg/1024px-Vasco_da_Gama%2C_by_Antonio_Manuel_da_Fonseca.jpg' alt='Vasco da Gama'> <h3>1.4 Expansão do Império e Consequências Globais</h3> <p>Abordaremos a expansão do Império Português ao longo dos séculos XVI e XVII, com a conquista de territórios na África, Ásia e América do Sul. Discutiremos as consequências sociais, econômicas e culturais dos Descobrimentos, como o comércio de especiarias, a difusão da cultura portuguesa e o impacto no desenvolvimento global.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Territorios_Portugueses.png/1280px-Territorios_Portugueses.png' alt='Mapa do Império Português'>"
//     },
//     {
//         "title": "Módulo 6: Dinastia Filipina, Restauração e  Monarquia Absolutista",
//         "html": "<h2>1. União Ibérica e Crise Dinástica</h2> <p>Neste módulo, analisaremos a União Ibérica, período em que Portugal e Espanha foram governados pelo mesmo rei, e a crise dinástica que levou à Restauração da Independência em 1640.</p> <h3>1.1  Dinastia Filipina e a União Ibérica (1580-1640)</h3> <p>Exploraremos a ascensão da Dinastia Filipina ao trono português em 1580, após a morte do rei D. Sebastião na Batalha de Alcácer Quibir, e a união das coroas de Portugal e Espanha sob o rei Filipe II. Abordaremos as implicações dessa união para Portugal, como a perda de autonomia política e o envolvimento em conflitos externos da Espanha.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Philip_II_of_Spain.jpg/800px-Philip_II_of_Spain.jpg' alt='Filipe II da Espanha'> <h3>1.2 Resistência e a Restauração da Independência</h3> <p>Analisaremos a resistência portuguesa à dominação espanhola, culminando na Restauração da Independência em 1640, com a aclamação de D. João IV como rei de Portugal.</p> <h2>2. Dinastia de Bragança e Absolutismo</h2> <p>Abordaremos a Dinastia de Bragança, que governou Portugal de 1640 a 1910, e a consolidação do absolutismo monárquico.</p> <h3>2.1 Consolidação da Independência e Guerras de Restauração</h3> <p>Exploraremos os desafios enfrentados por Portugal para consolidar sua independência após 1640, as Guerras de Restauração contra a Espanha e o papel de D. João IV e seus sucessores nesse processo.</p> <h3>2.2 Absolutismo Monárquico e Reorganização do Estado</h3> <p>Analisaremos a centralização do poder real em Portugal, a formação de um Estado absolutista e as reformas administrativas implementadas durante o reinado de D. João V no século XVIII.</p> <h3>2.3 Impacto do Ouro Brasileiro</h3> <p>Abordaremos o impacto do ouro brasileiro na economia portuguesa durante o século XVIII, o desenvolvimento de Lisboa e a construção de edifícios como o Palácio Nacional de Mafra, símbolo do poder da monarquia absolutista.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Palácio_Nacional_de_Mafra.jpg/1280px-Palácio_Nacional_de_Mafra.jpg' alt='Palácio Nacional de Mafra'>"
//     },
//     {
//         "title": "Módulo 7:  Iluminismo, Reformas Pombalinas e Invasões Francesas",
//         "html": "<h2>1. Iluminismo e Reformas Pombalinas</h2> <p>Neste módulo, vamos explorar o impacto do Iluminismo em Portugal, com destaque para as reformas implementadas pelo Marquês de Pombal durante o reinado de D. José I.</p> <h3>1.1 Influência do Iluminismo e as Ideias Reformistas</h3> <p>Abordaremos a difusão das ideias iluministas em Portugal no século XVIII, o debate sobre a necessidade de reformas para modernizar o país e o papel de intelectuais e figuras políticas nesse processo.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Marqu%C3%AAs_de_Pombal.jpg/1024px-Marqu%C3%AAs_de_Pombal.jpg' alt='Marquês de Pombal'> <h3>1.2 Marquês de Pombal e a Reconstrução de Lisboa</h3> <p>Analisaremos as reformas implementadas pelo Marquês de Pombal, Primeiro-Ministro de D. José I, após o terremoto de 1755 que devastou Lisboa. Abordaremos a reconstrução da cidade, as reformas administrativas, educacionais e econômicas, e o impacto na sociedade portuguesa.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Lisbon_Pombaline_Downtown_Wikimedia_Commons.jpg/1024px-Lisbon_Pombaline_Downtown_Wikimedia_Commons.jpg' alt='Lisboa Pombalina'> <h2>2. Invasões Francesas e Crise Política</h2> <p>Neste ponto, abordaremos as Guerras Napoleônicas e o impacto das invasões francesas em Portugal no início do século XIX.</p> <h3>2.1 Guerras Napoleônicas e Invasão Francesa</h3> <p>Analisaremos as Guerras Napoleônicas, o contexto da invasão francesa de Portugal em 1807 e a fuga da família real portuguesa para o Brasil.</p> <h3>2.2 Resistência e Guerra Peninsular</h3> <p>Abordaremos a resistência portuguesa à ocupação francesa, a Guerra Peninsular, com a participação de forças britânicas, e a expulsão dos franceses em 1811.</p> <h3>2.3 Crise Política e o Caminho para o Liberalismo</h3> <p>Analisaremos as consequências da invasão francesa para Portugal, a crise política e social, o surgimento de ideias liberais e o debate sobre a necessidade de reformas políticas e sociais.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Batalha_do_bu%C3%A7aco.jpg/1280px-Batalha_do_bu%C3%A7aco.jpg' alt='Batalha do Buçaco'>"
//     },
//     {
//         "title": "Módulo 8:  Liberalismo, Guerras Civis e Regeneração",
//         "html": "<h2>1. Revolução Liberal e Guerras Civis</h2> <p>Este módulo abordará a Revolução Liberal de 1820 em Portugal, a instauração de uma monarquia constitucional e as guerras civis que marcaram a primeira metade do século XIX.</p> <h3>1.1 Revolução de 1820 e a Constituição de 1822</h3> <p>Analisaremos a Revolução Liberal de 1820, as suas causas, o estabelecimento de uma monarquia constitucional e a promulgação da Constituição de 1822, inspirada em princípios liberais.</p> <h3>1.2 Guerras Civis: Liberais vs. Absolutistas</h3> <p>Exploraremos as guerras civis entre liberais e absolutistas, o confronto entre D. Pedro IV e D. Miguel pelo trono português, e a vitória final dos liberais em 1834.</p> <h2>2. Período da Regeneração e Desenvolvimento Econômico</h2> <p>Abordaremos o período da Regeneração, marcado pela estabilidade política e pelo desenvolvimento econômico.</p> <h3>2.1  Consolidação do Regime Liberal</h3> <p>Analisaremos a consolidação do regime liberal após as guerras civis, a estabilidade política proporcionada pela Carta Constitucional de 1826 e o papel de figuras importantes como o Duque de Saldanha.</p> <h3>2.2  Desenvolvimento Econômico e Industrialização</h3> <p>Exploraremos o desenvolvimento econômico de Portugal durante a Regeneração, com a expansão da agricultura, a construção de infraestruturas como ferrovias e o início da industrialização. Abordaremos o papel do Fontismo nesse processo.</p> <h3>2.3  Crise do Final do Século XIX</h3> <p>Analisaremos a crise econômica e social que marcou o final do século XIX em Portugal, o Ultimato Britânico de 1890, que abalou o orgulho nacional, e o crescente descontentamento com a monarquia.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Fontes_Pereira_de_Melo.jpg/1024px-Fontes_Pereira_de_Melo.jpg' alt='Fontes Pereira de Melo'>"
//     },
//     {
//         "title": "Módulo 9: Primeira República e Estado Novo",
//         "html": "<h2>1. Implantação da República e Primeira República</h2> <p>Neste módulo, abordaremos a implantação da República em Portugal em 1910 e os desafios enfrentados durante a Primeira República.</p> <h3>1.1  Queda da Monarquia e Proclamação da República</h3> <p>Analisaremos os fatores que levaram à queda da monarquia em 1910, como o descontentamento social, a crise econômica e o crescimento do republicanismo. Abordaremos a proclamação da República em 5 de outubro de 1910.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Proclamacao_da_Republica_1910.jpg/1280px-Proclamacao_da_Republica_1910.jpg' alt='Proclamação da República'> <h3>1.2  Primeira República: Instabilidade e Golpes de Estado</h3> <p>Exploraremos os desafios enfrentados pela Primeira República, como a instabilidade política, os golpes de estado, a participação de Portugal na Primeira Guerra Mundial e a crise econômica e social. Abordaremos a figura de Sidónio Pais e sua tentativa de estabelecer um regime presidencialista.</p> <h2>2. Estado Novo: Ditadura e Salazarismo</h2> <p>Analisaremos a ascensão do Estado Novo, ditadura liderada por António de Oliveira Salazar, que governou Portugal de 1933 a 1974.</p> <h3>2.1 Golpe de Estado de 1926 e a Ditadura Militar</h3> <p>Abordaremos o golpe de estado de 1926, que pôs fim à Primeira República, e a instauração de uma ditadura militar, preparando o caminho para a ascensão de Salazar ao poder.</p> <h3>2.2  António de Oliveira Salazar e a Implantação do Estado Novo</h3> <p>Analisaremos a figura de António de Oliveira Salazar, seu papel na estabilização econômica de Portugal e na implantação do Estado Novo em 1933, regime autoritário que se baseava em princípios nacionalistas, conservadores e católicos.</p> <h3>2.3  Características do Estado Novo: Repressão, Censura e Colonialismo</h3> <p>Exploraremos as principais características do Estado Novo, como a repressão política, a censura, o controle da economia, a política colonial e a resistência ao regime.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Ant%C3%B3nio_de_Oliveira_Salazar_1950s.jpg/1024px-Ant%C3%B3nio_de_Oliveira_Salazar_1950s.jpg' alt='António de Oliveira Salazar'>"
//     },
//     {
//         "title": "Módulo 10: Revolução dos Cravos, Democracia e Portugal Contemporâneo",
//         "html": "<h2>1. Revolução dos Cravos e Transição Democrática</h2> <p>Neste módulo, abordaremos a Revolução dos Cravos de 1974, que pôs fim ao Estado Novo, e a transição democrática em Portugal.</p> <h3>1.1  Contexto Histórico e as Causas da Revolução</h3> <p>Analisaremos o contexto histórico que levou à Revolução dos Cravos, como o desgaste do regime salazarista, as guerras coloniais em África, o descontentamento social e o papel dos movimentos de oposição.</p> <h3>1.2  25 de Abril de 1974: O Dia da Liberdade</h3> <p>Exploraremos os eventos do 25 de abril de 1974, a revolta militar liderada pelo Movimento das Forças Armadas (MFA), a queda do regime e a instauração da democracia em Portugal.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Cravos_revolucao.jpg/1024px-Cravos_revolucao.jpg' alt='Cravos da Revolução'> <h3>1.3  Processo Revolucionário em Curso (PREC)</h3> <p>Abordaremos o Processo Revolucionário em Curso (PREC), período de instabilidade política e social que se seguiu à Revolução, marcado por debates sobre o futuro de Portugal, a descolonização e a construção de um novo sistema político.</p> <h3>1.4  Consolidação da Democracia e a Constituição de 1976</h3> <p>Analisaremos a consolidação da democracia em Portugal, a aprovação da Constituição de 1976, que estabeleceu um regime democrático e os desafios enfrentados pelo país na transição para a democracia.</p> <h2>2. Portugal Contemporâneo: Integração Europeia e Desafios do Século XXI</h2> <p>Neste ponto, exploraremos a história recente de Portugal, a integração na União Europeia e os desafios do século XXI.</p> <h3>2.1  Adesão à União Europeia e seus Impactos</h3> <p>Analisaremos a adesão de Portugal à Comunidade Económica Europeia (CEE) em 1986, os benefícios da integração europeia para Portugal, como o desenvolvimento econômico e a modernização do país.</p> <h3>2.2  Desafios Económicos e Sociais do Século XXI</h3> <p>Abordaremos os desafios econômicos e sociais enfrentados por Portugal no século XXI, como a crise financeira de 2008, as políticas de austeridade, o desemprego e a necessidade de reformas para garantir a sustentabilidade do modelo social europeu.</p> <h3>2.3  Portugal no Contexto Global: Relações Internacionais e Futuro</h3> <p>Exploraremos o papel de Portugal no contexto global, suas relações internacionais, a participação em organizações internacionais e os desafios e oportunidades que o país enfrenta no século XXI.</p> <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/1280px-Flag_of_Europe.svg.png' alt='Bandeira da União Europeia'>"
//     }
// ]